version: "2.3"

services:
  
  ros2-rclgo-pub:
    build: .
    image: ros2/rclgo-bouncy
    network_mode: bridge
    entrypoint: /bin/bash -c "cd /home/rclgo/go/src/rclgo/publisher && source /opt/ros/bouncy/setup.bash && go test"    

  ros2-rclgo-sub:
    build: .
    image: ros2/rclgo-bouncy
    network_mode: bridge
    entrypoint: /bin/bash -c "cd /home/rclgo/go/src/rclgo/subscription && source /opt/ros/bouncy/setup.bash && go test"    

