package stdmsgs

import (
	"bytes"
	"encoding/binary"
	"fmt"
)

// Automated generation with types/generator/app/generator.go
// This Generator is still under development,
// some imported comments may not make any sence,
// therefore it is recommended to look at the respective .msg/.srv original file.

// Int64 Autogenerated Struct
type Int64 struct {
	// Data Autogenerated Comment
	Data int64
}

// ParseBytes TODO
func (msg *Int64) ParseBytes(data []byte) error {

	buf := bytes.NewBuffer(data)
	binary.Read(buf, binary.LittleEndian, &msg.Data)

	return nil
}

// ToString TOOD
func (msg *Int64) ToString() string {
	return fmt.Sprintf("%d", msg.Data)
}
