package types
/////////////////////////////////////////////////////
//// THE CONTENT OF THIS FILE HAS BEEN AUTOGENERATED
/////////////////////////////////////////////////////
// #cgo CFLAGS: -I/opt/ros/bouncy/include
// #cgo LDFLAGS: -L/opt/ros/bouncy/lib -lrcl -lrosidl_generator_c -lrosidl_typesupport_c -lstd_msgs__rosidl_generator_c -lstd_msgs__rosidl_typesupport_c
// #include "msg_types.h"
import "C"
import "unsafe"


type StdMsgsInt32 struct {
	data    *C.std_msgs__msg__Int32
	MsgType MessageTypeSupport
}

func (msg *StdMsgsInt32) GetMessage() MessageTypeSupport {
	return msg.MsgType
}

func (msg *StdMsgsInt32) GetData() MessageData {
	return MessageData{unsafe.Pointer(msg.data)}
}

func (msg *StdMsgsInt32) InitMessage() {
	msg.data = C.init_std_msgs_msg_Int32()
	msg.MsgType = GetMessageTypeFromStdMsgsInt32()
}

func (msg *StdMsgsInt32) SetInt32(data int32) {
	//TODO: to implement the setter
	msg.data.data = C.int(data)
}

func (msg *StdMsgsInt32) GetInt32() int32 {
	return int32(msg.data.data)
}

func (msg *StdMsgsInt32) GetDataAsString() string {
	//TODO: to implement the stringify opt
	myRetValue:=""
	return myRetValue
}

func (msg *StdMsgsInt32) DestroyMessage() {
	C.destroy_std_msgs_msg_Int32(msg.data)
}

func GetMessageTypeFromStdMsgsInt32() MessageTypeSupport {
	return MessageTypeSupport{C.get_message_type_from_std_msgs_msg_Int32()}
}
