package types

/////////////////////////////////////////////////////
//// THE CONTENT OF THIS FILE HAS BEEN AUTOGENERATED
/////////////////////////////////////////////////////
// #cgo CFLAGS: -I /opt/ros/crystal/include
// #cgo LDFLAGS: -L /opt/ros/crystal/lib -lrcl -lrosidl_generator_c -lrosidl_typesupport_c -lstd_msgs__rosidl_generator_c -lstd_msgs__rosidl_typesupport_c
// #include "msg_types.h"
import "C"
import "unsafe"

type StdMsgsUInt8 struct {
	data    *C.std_msgs__msg__UInt8
	MsgType MessageTypeSupport
}

func (msg *StdMsgsUInt8) GetMessage() MessageTypeSupport {
	return msg.MsgType
}

func (msg *StdMsgsUInt8) GetData() MessageData {
	return MessageData{unsafe.Pointer(msg.data)}
}

func (msg *StdMsgsUInt8) InitMessage() {
	msg.data = C.init_std_msgs_msg_UInt8()
	msg.MsgType = GetMessageTypeFromStdMsgsUInt8()
}

func (msg *StdMsgsUInt8) SetUInt8(data uint8) {
	//TODO: to implement the setter
	msg.data.data = C.uchar(data)
}

func (msg *StdMsgsUInt8) GetUInt8() uint8 {
	return uint8(msg.data.data)
}

func (msg *StdMsgsUInt8) GetDataAsString() string {
	//TODO: to implement the stringify opt
	myRetValue := ""
	return myRetValue
}

func (msg *StdMsgsUInt8) DestroyMessage() {
	C.destroy_std_msgs_msg_UInt8(msg.data)
}

func GetMessageTypeFromStdMsgsUInt8() MessageTypeSupport {
	return MessageTypeSupport{C.get_message_type_from_std_msgs_msg_UInt8()}
}
