package types
/////////////////////////////////////////////////////
//// THE CONTENT OF THIS FILE HAS BEEN AUTOGENERATED
/////////////////////////////////////////////////////
// #cgo CFLAGS: -I/opt/ros/eloquent/include
// #cgo LDFLAGS: -L/opt/ros/eloquent/lib -lrcl -lrosidl_generator_c -lrosidl_typesupport_c -lstd_msgs__rosidl_generator_c -lstd_msgs__rosidl_typesupport_c
// #include "msg_types.h"
import "C"
import "unsafe"


type StdMsgsUInt32 struct {
	data    *C.std_msgs__msg__UInt32
	MsgType MessageTypeSupport
}

func (msg *StdMsgsUInt32) GetMessage() MessageTypeSupport {
	return msg.MsgType
}

func (msg *StdMsgsUInt32) GetData() MessageData {
	return MessageData{unsafe.Pointer(msg.data)}
}

func (msg *StdMsgsUInt32) InitMessage() {
	msg.data = C.init_std_msgs_msg_UInt32()
	msg.MsgType = GetMessageTypeFromStdMsgsUInt32()
}

func (msg *StdMsgsUInt32) SetUInt32(data uint32) {
	//TODO: to implement the setter
	msg.data.data = C.uint(data)
}

func (msg *StdMsgsUInt32) GetUInt32() uint32 {
	return uint32(msg.data.data)
}

func (msg *StdMsgsUInt32) GetDataAsString() string {
	//TODO: to implement the stringify opt
	myRetValue:=""
	return myRetValue
}

func (msg *StdMsgsUInt32) DestroyMessage() {
	C.destroy_std_msgs_msg_UInt32(msg.data)
}

func GetMessageTypeFromStdMsgsUInt32() MessageTypeSupport {
	return MessageTypeSupport{C.get_message_type_from_std_msgs_msg_UInt32()}
}
