package types
/////////////////////////////////////////////////////
//// THE CONTENT OF THIS FILE HAS BEEN AUTOGENERATED
/////////////////////////////////////////////////////
// #cgo CFLAGS: -I/opt/ros/bouncy/include
// #cgo LDFLAGS: -L/opt/ros/bouncy/lib -lrcl -lrosidl_generator_c -lrosidl_typesupport_c -lstd_msgs__rosidl_generator_c -lstd_msgs__rosidl_typesupport_c
// #include "msg_types.h"
import "C"
import "unsafe"


type StdMsgsUInt64 struct {
	data    *C.std_msgs__msg__UInt64
	MsgType MessageTypeSupport
}

func (msg *StdMsgsUInt64) GetMessage() MessageTypeSupport {
	return msg.MsgType
}

func (msg *StdMsgsUInt64) GetData() MessageData {
	return MessageData{unsafe.Pointer(msg.data)}
}

func (msg *StdMsgsUInt64) InitMessage() {
	msg.data = C.init_std_msgs_msg_UInt64()
	msg.MsgType = GetMessageTypeFromStdMsgsUInt64()
}

func (msg *StdMsgsUInt64) SetUInt64(data uint64) {
	//TODO: to implement the setter
	msg.data.data = C.ulong(data)
}

func (msg *StdMsgsUInt64) GetUInt64() uint64 {
	return uint64(msg.data.data)
}

func (msg *StdMsgsUInt64) GetDataAsString() string {
	//TODO: to implement the stringify opt
	myRetValue:=""
	return myRetValue
}

func (msg *StdMsgsUInt64) DestroyMessage() {
	C.destroy_std_msgs_msg_UInt64(msg.data)
}

func GetMessageTypeFromStdMsgsUInt64() MessageTypeSupport {
	return MessageTypeSupport{C.get_message_type_from_std_msgs_msg_UInt64()}
}
