package types
/////////////////////////////////////////////////////
//// THE CONTENT OF THIS FILE HAS BEEN AUTOGENERATED
/////////////////////////////////////////////////////
// #cgo CFLAGS: -I/opt/ros/bouncy/include
// #cgo LDFLAGS: -L/opt/ros/bouncy/lib -lrcl -lrosidl_generator_c -lrosidl_typesupport_c -lstd_msgs__rosidl_generator_c -lstd_msgs__rosidl_typesupport_c
// #include "msg_types.h"
import "C"
import "unsafe"


type StdMsgsInt16 struct {
	data    *C.std_msgs__msg__Int16
	MsgType MessageTypeSupport
}

func (msg *StdMsgsInt16) GetMessage() MessageTypeSupport {
	return msg.MsgType
}

func (msg *StdMsgsInt16) GetData() MessageData {
	return MessageData{unsafe.Pointer(msg.data)}
}

func (msg *StdMsgsInt16) InitMessage() {
	msg.data = C.init_std_msgs_msg_Int16()
	msg.MsgType = GetMessageTypeFromStdMsgsInt16()
}

func (msg *StdMsgsInt16) SetInt16(data int16) {
	//TODO: to implement the setter
	msg.data.data = C.short(data)
}

func (msg *StdMsgsInt16) GetInt16() int16 {
	return int16(msg.data.data)
}

func (msg *StdMsgsInt16) GetDataAsString() string {
	//TODO: to implement the stringify opt
	myRetValue:=""
	return myRetValue
}

func (msg *StdMsgsInt16) DestroyMessage() {
	C.destroy_std_msgs_msg_Int16(msg.data)
}

func GetMessageTypeFromStdMsgsInt16() MessageTypeSupport {
	return MessageTypeSupport{C.get_message_type_from_std_msgs_msg_Int16()}
}
