package types

/////////////////////////////////////////////////////
//// THE CONTENT OF THIS FILE HAS BEEN AUTOGENERATED
/////////////////////////////////////////////////////
// #cgo CFLAGS: -I/opt/ros/eloquent/include
// #cgo LDFLAGS: -L/opt/ros/eloquent/lib -Wl,-rpath=/opt/ros/eloquent/lib -lrcl -lrosidl_generator_c -lrosidl_typesupport_c -lstd_msgs__rosidl_generator_c -lstd_msgs__rosidl_typesupport_c
// #include <rcl/rcl.h>
import "C"

import (
	"unsafe"

	"github.com/richardrigby/rclgo/cwrap"
)

type StdMsgsInt32 struct {
	data    *cwrap.StdMsgs_MsgInt32
	MsgType MessageTypeSupport
}

func (msg *StdMsgsInt32) GetMessage() MessageTypeSupport {
	return msg.MsgType
}

func (msg *StdMsgsInt32) GetData() MessageData {
	return MessageData{unsafe.Pointer(msg.data)}
}

func (msg *StdMsgsInt32) InitMessage() {
	msg.data = cwrap.InitStdMsgsMsgInt32()
	msg.MsgType = GetMessageTypeFromStdMsgsInt32()
}

func (msg *StdMsgsInt32) SetInt32(data int32) {
	//TODO: to implement the setter
	msg.data.Set(data)
}

func (msg *StdMsgsInt32) GetInt32() int32 {
	return int32(msg.data.Data())
}

func (msg *StdMsgsInt32) GetDataAsString() string {
	//TODO: to implement the stringify opt
	myRetValue := ""
	return myRetValue
}

func (msg *StdMsgsInt32) DestroyMessage() {
	cwrap.DestroyStdMsgsMsgInt32(msg.data)
}

func GetMessageTypeFromStdMsgsInt32() MessageTypeSupport {
	ret := cwrap.GetMessageTypeFromStdMsgsMsgInt32()
	return MessageTypeSupport{ret}
}
