name: CI
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master


jobs:
  rclgo-testing-example:
    runs-on: ubuntu-latest

    steps:
    - name: "Checkout the repository"
      uses: actions/checkout@v1
    
    - name: Generate the docker images
      run: docker-compose build
      working-directory: ./rclgo
    
    - name: Check docker images have been generated
      run: docker ps -a
    
    - name: Execute containers during 1 minute and save output
      run: docker-compose up >  mylog.txt
      working-directory: ./rclgo
      timeout-minutes: 1
      
    - name: Save artifacts
      uses: actions/upload-artifact@v1
      with:
          name: 'rcl_go_greeter_$(date +"%Y_%m_%d_%I_%M").txt'
          path: ./rclgo/mylog.txt
          

